package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"
	"template-go/internal/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	user, err := r.UserService.CreateUser(input.Username, input.Password, input.FullName, input.Email)
	if err != nil {
		return nil, fmt.Errorf("error inserting new user: %v", err)
	}
	userModel := &model.User{
		Username: user.Username,
		FullName: user.FullName,
		ID:       user.ID.String(),
		Email:    user.Email,
	}
	return userModel, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pageID int, pageSize int) ([]*model.User, error) {
	offset := (pageID - 1) * pageSize
	result, err := r.UserService.ListUsers(&pageSize, &offset)
	if err != nil {
		return nil, err
	}
	var users []*model.User
	for _, user := range result {
		users = append(users, &model.User{
			ID:       user.ID.String(),
			FullName: user.FullName,
			Username: user.Username,
			Email:    user.Email,
		})
	}
	return users, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
type userResolver struct{ *Resolver }
